# Generated by Django 4.0.4 on 2022-05-20 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MealItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_created=True)),
                ('meal_name', models.CharField(max_length=255)),
                ('meal_type', models.CharField(max_length=10)),
                ('day_of_week', models.CharField(max_length=10)),
            ],
        ),
    ]
